const UserActionTypes = {
  REGISTER_START: "REGISTER_START",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_START: "LOGIN_START",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT_START: "LOGOUT_START",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  SET_MESSAGE: "SET_MESSAGE"
};

export default UserActionTypes;